### ISSUE TITLE
有个BUG

### ISSUE THREAD

**Issue by linwk24** [szvone/vmqApk#11]
支付宝付款方名字昵称带有阿拉伯数字时,会把昵称里是数字当成金额通知过去,导致真实金额订单失败。

**Comment by huangfengye** [comment]
我也遇到这个问题了，下面是一个修复方法
`    public static String getMoney(String content){
        int xnzf_index;
        int index = content.indexOf("]");
        if (index!=-1){
            content = content.substring(index+1);
        }
        xnzf_index=content.indexOf("向你支付");
        content = content.substring(xnzf_index);

        Pattern p = Pattern.compile("([0-9]\\d*\\.?\\d*)|(0\\.\\d*[0-9])");
        Matcher m = p.matcher(content);
        boolean result = m.find();
        String find_result = null;
        if (result) {
            find_result = m.group(1);
        }
        return find_result;
    }	`

**Comment by linwk24** [comment]
非常感情 重新编译完美解决

**Comment by 2675553** [comment]
你们用哪个版本的编译器。我老编译失败

**Comment by huangfengye** [comment]
缺少依赖吧？？源码直接是编译不了的，得直接改改。

**Comment by huangfengye** [comment]
> 你们用哪个版本的编译器。我老编译失败
> 
> ![cJ2PteKNjkVFo89](https://user-images.githubusercontent.com/37089234/70204748-ade33480-175c-11ea-83b9-83f46419f520.png)

缺少依赖吧？？源码直接是编译不了的，得直接改改。

**Comment by szvone** [comment]
+ v1.8.1（2019.12.20）
    + 修复上个版本无法正常回调问题

 + v1.8（2019.12.03）
    + 修复付款人昵称如果是纯数字，支付完后台订单金额会记录成昵称的数字的问题
