### ISSUE TITLE
希望监控端能够提供状态查询

### ISSUE THREAD

**Issue by 2675553** [szvone/vmqApk#15]
希望作者 添加app 的8080端口，返回一些json，

以便网页端拉取 查询app是否掉线，或锁屏后被杀死，的问题

再有就是希望 作者给app 一个版本显示，

装了app 我都不知道自己装的是1.6 还是1.7  

谢谢，目前来说是非常好的源码了，希望继续加油

我暂时还没接入系统，也没发做更多的评论，

待api接口 能查询 监控端app状态在线与否的时候 ，再来用看看

这个接口不知道是不是查询app监控端的
/getState？t=1547613643&sign=7db2d26323dd8ccbb5d130dd61d210a0
我反正把手机断网了，杀死了app  这返回的还是 1
{"code":1,"msg":"成功","data":{"lastpay":"1547394640","lastheart":"1547613873","state":"1"}}

如果是查询服务端 php或者java的感觉没什么必要，这个接口，

因为网站能打开 就说明可以用接口了，谢谢，希望作者看到能回复下

**Comment by 2675553** [comment]
再有，
发现监控端发送心跳比较频繁，5秒还是多少就发一次心跳，

希望能改成自定义心跳频率，

**Comment by szvone** [comment]
心跳频率忘记是多久了 应该是30秒，手机断网后，心跳自动停止，服务端会有个心跳超时，当达到超时时间后监控端状态会自动变为异常，该接口是查询监控端状态，不是查询服务端状态，请认真查看文档

**Comment by 2675553** [comment]
谢谢作者回复，深入了解了下，其实设计的 流程都很合理，

就是希望能增加上app的版本显示，以及自定义更新监控的频率就好了

本来想自己编译的，一直提示报错，没法编译， 不知道您是用的哪个版本的 安卓编译工具
