### ISSUE TITLE
1.8版本无法回调

### ISSUE THREAD

**Issue by BrkOne** [szvone/vmqApk#17]
手机环境安装1.7版本一切正常

安装1.8版本
检测心跳：正常
检测监听：监听正常
但是微信和支付宝都无法回调

**Comment by qq9349540** [comment]
完全监听不到微信和支付宝的消息 其他正常

**Comment by qq9349540** [comment]
发现监听类没写全

**Comment by 2675553** [comment]
能用了吗

**Comment by qq9349540** [comment]
> 能用了吗

基本做了下修改已经基本完善了，安卓4.1以下要用辅助功能类实现，4.1以上可以用监听重写的方法实现。
不知道怎么提交PR。。。。。
顺便做了下二次开发，支持多用户和应用多开的形式

**Comment by inbjo** [comment]
> > 能用了吗
> 
> 基本做了下修改已经基本完善了，安卓4.1以下要用辅助功能类实现，4.1以上可以用监听重写的方法实现。
> 不知道怎么提交PR。。。。。
> 顺便做了下二次开发，支持多用户和应用多开的形式

fork这个项目 然后修改好你的代码 在到这个项目 点击pull request 再点击new pull request 提交合并请求即可。

**Comment by szvone** [comment]
+ v1.8.1（2019.12.20）
    + 修复上个版本无法正常回调问题
