### ISSUE TITLE
监控出现错误的无订单转账

### ISSUE THREAD

**Issue by huangfengye** [szvone/vmqApk#21]
![QQ截图20200104130159](https://user-images.githubusercontent.com/26798988/71764112-7fed3d80-2f1e-11ea-812b-a91d873d2be1.jpg)
)

**Comment by huangfengye** [comment]
![68747470733a2f2f7075752e73682f45576463312f333431323838343230632e6a7067](https://user-images.githubusercontent.com/26798988/71764121-9b584880-2f1e-11ea-8a43-82819ba87059.jpg)

**Comment by 2675553** [comment]
看不到图，，，另外1.81版本你们能安装吗。
我怎么安装失败，是不是没签名

**Comment by 2675553** [comment]
无订单转账，是你没生成 订单，就扫码就是这样的，

朋友扫你码，没通过网站， 这个app也会上传数据的，就这样了

**Comment by huangfengye** [comment]
> 无订单转账，是你没生成 订单，就扫码就是这样的，
> 
> 朋友扫你码，没通过网站， 这个app也会上传数据的，就这样了

你看不到我的图就 请你不要乱说，OK？？你以为我不知道正常情况下没订单就会出无订单转载吗？？

**Comment by 2675553** [comment]
> > 无订单转账，是你没生成订单，就扫码就是这样的，
> > 朋友扫你码，没通过网站，这个app也会上传数据的，就这样了
> 
> 你看不到我的图就请你不要乱说，OK ？？你以为我不知道正常情况下没订单就会出无订单转载吗？？？

你这人怎么这样啊，好心告诉你还这口气，告辞

**Comment by uoboy** [comment]
模拟器和华为手机安装监控端1.8.1最新版,显示正常监控，扫码支付付款了，后台订单状态还是未支付？请问老师们什么情况能给我点技术指导么？谢谢了

**Comment by huangfengye** [comment]
> 模拟器和华为手机安装监控端1.8.1最新版,显示正常监控，扫码支付付款了，后台订单状态还是未支付？请问老师们什么情况能给我点技术指导么？谢谢了
建议用原生系统的手机。

**Comment by huangfengye** [comment]
> 模拟器和华为手机安装监控端1.8.1最新版,显示正常监控，扫码支付付款了，后台订单状态还是未支付？请问老师们什么情况能给我点技术指导么？谢谢了

建议用原生系统的手机。

**Comment by huangfengye** [comment]
完美解决方案
String content ="9向你付款1,160.00元"
```
public static String getMoney(String content){
        content = content.replace(",", "");
       // 过滤掉订单中的逗号，“9向你付款1,160.00元”  变成”9向你付款1160.00元”
        int xnzf_index,y_index;
        int index = content.indexOf("]");
        if (index!=-1){
            content = content.substring(index+1);
        }
        xnzf_index=content.lastIndexOf("款");
        //截取最后一个"款"字
        y_index   =content.lastIndexOf("元");
        //截取最后一个"元"字
        find_result = content.substring(xnzf_index+1,y_index); 
        //”9向你付款1160.00元” 变“1160.00”
        //1160.00”中的数值即为 金额       
        return find_result;
    }
```

**Comment by fakers777** [comment]
@huangfengye 你的店员收款正常吗

**Comment by huangfengye** [comment]
> @huangfengye 你的店员收款正常吗

前几天测试过，正常。

**Comment by wmgm183** [comment]
真香
