### ISSUE TITLE
新版支付宝解决方案

### ISSUE THREAD

**Issue by dreamncn** [szvone/vmqApk#33]
之前版本的支付宝不受影响，主要是这个作者太久没更新了...
新版本的支付宝修改了通知内容，老版本的监控端已经无法处理支付宝消息了
https://github.com/dreamncn/vmqApk/releases/tag/v1.8.2

**Comment by ghost** [comment]
大佬有没有遇到微信不弹出通知的情况

权限通知啥的都打开的

**Comment by wngx99** [comment]
安装了，支付宝依然不行。

**Comment by wngx99** [comment]
另外，下载的是apk文件，安装之后，版本还是显示的1.81

**Comment by dreamncn** [comment]
之前传错版本了，已更新
