### ISSUE TITLE
请作者视情况进行合并，代码是想到什么改什么，造成了很多垃圾提交

### ISSUE THREAD

**Issue by wmgm183** [szvone/vmqApk#54]
安卓8还是不能监听通知啊
vivoy97 v1813a 安卓8.1.0系统通知栏没看到弹出啊
https://github.com/zwc456baby/vmqApk

**Comment by cysell** [comment]
连接池数量为0时有延迟，建议改成1
".connectionPool(new ConnectionPool(0, 5, TimeUnit.SECONDS))"
to
".connectionPool(new ConnectionPool(1, 5, TimeUnit.SECONDS))"

**Comment by wmgm183** [comment]
> 连接池数量为0时有延迟，建议改成1 ".connectionPool(new ConnectionPool(0, 5, TimeUnit.SECONDS))" to ".connectionPool(new ConnectionPool(1, 5, TimeUnit.SECONDS))"

老哥 你的用什么版本安卓监听的。目前只能是6

**Comment by cysell** [comment]
我用小米11测试时，发现连接池数量为0时点击按钮没反应
